### ISSUE TITLE
Conflicting Hook Name

### ISSUE THREAD

**Issue by anzati1** [Blu-x92/LUNA_SWORD_COMBAT_SYSTEM#1]
[https://github.com/Blu-x92/LUNA_SWORD_COMBAT_SYSTEM/blob/f4310f2ea240df292599db223e0ef5a38eddfe6e/lscs_public/lua/lscs/autorun/lscs_forcepowers.lua#L184](url)
`hook.Add( "StartCommand", "StartCommandExample", function( ply, cmd )`

**Comment by Blu-x92** [comment]
#4c137da7769cd5b383f8c02d3d55b7183938e7c1
