### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by SgtWarbuff** [Blu-x92/LUNA_SWORD_COMBAT_SYSTEM#3]
I am having an Issue with the animations. The character does not move or do any of the animations when I use the sabers. The only stance that shows an animation is the "Untrained" stance. all the others don't use animations.

**Comment by SgtWarbuff** [comment]
I looked through any issues in the problems section of Gmod, and I am not seeing anything related to this mod.

**Comment by Blu-x92** [comment]
read
https://steamcommunity.com/workshop/filedetails/discussion/2837856621/3469478215304046487/
