### ISSUE TITLE
Items won't get to the inventory

### ISSUE THREAD

**Issue by Prokna666** [Blu-x92/LUNA_SWORD_COMBAT_SYSTEM#4]
When i'm taking a LSCS lightsaber hilt, crystal, force powers or stances, they aren't adding to my inventory after pressing E.

**Comment by Blu-x92** [comment]
i wouldnt have released this addon if it wasnt working at all. The issue is on your side and has a 99% chance of being a addon conflict. Most likely something that is messing with item pickup. 
There is nothing else i can do for you. Clean your game is the only solution i can give you.
