### ISSUE TITLE
No Lightsaber inhand

### ISSUE THREAD

**Issue by AxFive** [Blu-x92/LUNA_SWORD_COMBAT_SYSTEM#9]
So my Problem is that i don't have an Lightsaber inhand even tho i equipped a Stance, Hilt and Crystal. Console also does not spitout errors, i am confused

**Comment by Blu-x92** [comment]
no steps to reproduce = no fix,
report again when you can rule out a simple addon conflict // when you can report the conflicting addon

**Comment by Peekofwar** [comment]
Strangely, I'm having the same problem.

**Comment by AxFive** [comment]
My problem was the Addon Manual Weapon Pickup. check if you have the same installed, if so, uninstall it is not compatible

**Comment by Peekofwar** [comment]
> My problem was the Addon Manual Weapon Pickup. check if you have the same installed, if so, uninstall it is not compatible

Exact same incompatible addon...
I found that out by boing page by page disabling addons until it started working... That narrowed it down to one page, and from there I started working one-by-one until I discovered it was that, which was not an addon I ever would have expected to break this, but here we are.
